# Site settings
name: Hack A Bit
title: we are what we think
email: kavinyao@gmail.com
description: "Personal blog of Kavin Yao."
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

# Markdown settings
kramdown:
    input: GFM
