# Site settings
name: hack a bit
title: we are what we think
email: kavinyao@gmail.com
github: kavinyao
twitter: kavinyao
description: "Personal blog of Kavin Yao."
baseurl: ""
url: "http://hackab.it"

# Services
ga: UA-27956411-1
disqus: hackabit

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: post
    values:
      layout: post
      is_post: true
      author: "Kavin Yao"

# Markdown settings
kramdown:
    input: GFM
