#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 post-slug-you-want"
    exit 1
fi

file=posts/$1.md
echo "Creating $file..."
touch $file

echo "Creating nico post [source/$1/index.md]..."
mkdir source/$1
ln -s ../../$file source/$1/index.md

echo
echo "Open $file to edit."
